site_name: Arasaka
theme:
  name: material
  logo: assets/asa-logo-480.png
  favicon: assets/asa-logo-480.png
  language: ru
  features:
    - navigation.tabs
    - navigation.sections
    - content.tabs.link
  palette: 
    scheme: slate
    primary: black
    accent: red

extra_css:
  - extra.css

extra:
  generator: false

nav:
  - Главная: index.md
  - Вики:
      - Правила:
          - Discord: rules/discord.md
          - Клан: rules/clan.md
      - Роли: roles.md
      - ARC: arc.md
