site_name: Arasaka
theme:
  name: material
  logo: assets/asa-logo-480.png    # Добавил эту строку
  favicon: assets/asa-logo-480.png # И эту (для иконки вкладки)
  palette: 
    scheme: slate
    primary: black
    accent: red  # Сделал красные акценты под стиль Арасаки

nav:
  - Главная: index.md
  - Правила: rules.md
