site_name: Arasaka
theme:
  name: material
  logo: assets/asa-logo-480.png
  favicon: assets/asa-logo-480.png
  language: ru
  palette: 
    scheme: slate
    primary: black
    accent: red

nav:
  - Главная: index.md
  - Правила: rules.md
